package com.facetoe.jreader;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.concurrent.CancellationException;
import java.util.concurrent.ExecutionException;

/**
 * Created with IntelliJ IDEA.
 * User: facetoe
 * Date: 20/10/13
 * Time: 10:34 AM
 */
public class SetupWindow {
    JFrame frame = new JFrame("JReader Setup");
    private JPanel pnlParent;

    private JPanel pnlInfo;
    private JPanel pnlDocs;
    private JButton btnOK;
    private JButton btnCancel;
    private JProgressBar progressBar;
    private JLabel icnLocate;
    private JLabel icnParse;
    private JLabel icnExtract;
    private JLabel lblStatus;
    private JLabel lblInfo;
    private JLabel icnDownload;


    SetupWorker worker = new SetupWorker();


    public SetupWindow() {
        frame.setContentPane(pnlParent);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setVisible(true);

        btnOK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    worker.execute();
                } catch ( Exception e1 ) {
                    e1.printStackTrace();
                }
            }
        });

        btnCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                worker.cancel(true);
            }
        });
    }

    private void setLabelIcon(JLabel label, String iconPath) {
        BufferedImage icon = null;
        try {
            icon = ImageIO.read(new File(iconPath));
        } catch ( IOException e ) {
            e.printStackTrace();
        }
        label.setIcon(new ImageIcon(icon));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlParent = new JPanel();
        pnlParent.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        pnlParent.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20), null));
        pnlInfo = new JPanel();
        pnlInfo.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:d:grow"));
        pnlParent.add(pnlInfo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Locate Documentation");
        CellConstraints cc = new CellConstraints();
        pnlInfo.add(label1, cc.xy(1, 3));
        final JLabel label2 = new JLabel();
        label2.setText("Parse Documentation");
        pnlInfo.add(label2, cc.xy(1, 5));
        final JLabel label3 = new JLabel();
        label3.setText("Extract Java Source");
        pnlInfo.add(label3, cc.xy(1, 9));
        icnLocate = new JLabel();
        icnLocate.setText("Label");
        pnlInfo.add(icnLocate, cc.xy(3, 3));
        icnParse = new JLabel();
        icnParse.setText("Label");
        pnlInfo.add(icnParse, cc.xy(3, 5));
        icnExtract = new JLabel();
        icnExtract.setText("Label");
        pnlInfo.add(icnExtract, cc.xy(3, 9));
        final JLabel label4 = new JLabel();
        label4.setText("Download Java Source");
        pnlInfo.add(label4, cc.xy(1, 7));
        icnDownload = new JLabel();
        icnDownload.setText("Label");
        pnlInfo.add(icnDownload, cc.xy(3, 7));
        pnlDocs = new JPanel();
        pnlDocs.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        pnlParent.add(pnlDocs, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(20, 20), null, 0, false));
        progressBar = new JProgressBar();
        progressBar.setVisible(true);
        pnlDocs.add(progressBar, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        lblStatus = new JLabel();
        lblStatus.setText("Label");
        pnlDocs.add(lblStatus, cc.xy(1, 3));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        pnlParent.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Before you can use JReader we need to complete the following installation steps:");
        panel1.add(label5, cc.xy(1, 1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:384px:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        pnlParent.add(panel2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblInfo = new JLabel();
        lblInfo.setText("Please locate the Java Documentation on your system.");
        panel2.add(lblInfo, cc.xyw(1, 1, 3));
        btnOK = new JButton();
        btnOK.setText("OK");
        panel2.add(btnOK, cc.xy(1, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        btnCancel = new JButton();
        btnCancel.setText("Cancel");
        panel2.add(btnCancel, cc.xy(3, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlParent;
    }

    class SetupWorker extends SwingWorker<Boolean, String> {


        private void downloadSource() throws IOException {
            lblInfo.setText("Downloading Source");
            lblStatus.setText("Connecting...");

            FileDownloader downloader = new FileDownloader(Config.dataDirectory + Config.JAVA_LANG_ZIP,
                    "http://sourceforge.net/projects/jdk7src/files/latest/download");
            downloader.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    progressBar.setValue(( int ) e.getWhen());
                    lblStatus.setText("Downloaded " + e.getActionCommand());
                }
            });

            downloader.download();

            Config.setBool(Config.HAS_JAVALANG_SOURCE, true);
            setLabelIcon(icnDownload, "/home/facetoe/tmp/system_tick_alt_03.png");
            lblStatus.setText("Complete");
            progressBar.setValue(0);
        }

        private void extractSource() throws Exception {

            lblInfo.setText("Extracting Source");
            lblStatus.setText("Initializing...");

            String zipPath = Config.dataDirectory + Config.JAVA_LANG_ZIP;
            UnZipper unZipper = new UnZipper(zipPath, zipPath.replace(".zip", ""));
            unZipper.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    progressBar.setValue(( int ) e.getWhen());
                    lblStatus.setText(e.getActionCommand());
                }
            });
            unZipper.unzip();

            Config.setBool(Config.HAS_EXTRACTED_SOURCE, true);
            lblStatus.setText("Complete");
            setLabelIcon(icnExtract, "/home/facetoe/tmp/system_tick_alt_03.png");

        }

        private void setUpDefaultProfile(File docDir) throws IOException {
            String srcPath = Config.getString(Config.DATA_DIR)
                    + Config.JAVA_LANG_ZIP.replace(".zip", "")
                    + File.separator;

            ProfileManager profileManager = ProfileManager.getInstance();
            String javaDocsPath = docDir.getAbsolutePath() + File.separator + "api" + File.separator;
            profileManager.newProfile("Default", "default.ser", javaDocsPath, srcPath);

            profileManager.saveProfiles();
            Config.setBool(Config.HAS_DEFAULT_PROFILE, true);
            Config.setString(Config.CURRENT_PROFILE, "Default");
        }

        private void parseDocs(File docDir) throws Exception {
            lblInfo.setText("Parsing Documentation");
            lblStatus.setText("Loading...");
            String path = docDir.getAbsolutePath()
                    + File.separator
                    + "api"
                    + File.separator
                    + "allclasses-noframe.html"; //TODO fix this
            JavaDocParser parser = new JavaDocParser();

            parser.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    progressBar.setValue(0);
                    lblStatus.setText(e.getActionCommand());
                }
            });

            HashMap<String, String> classes = parser.parse(path);
            Utilities.writeCLassData(ProfileManager.getInstance().getPath()
                    + File.separator
                    + Config.CLASS_DATA_FILE_NAME, classes);

            Config.setBool(Config.HAS_PARSED_DOCS, true);
            lblStatus.setText("Complete");
            setLabelIcon(icnParse, "/home/facetoe/tmp/system_tick_alt_03.png");
        }

        @Override
        protected Boolean doInBackground() throws Exception {
            JReaderSetup.createDirectoriesAndConfig();
            File docDir = JReaderSetup.chooseDocs();
            if ( docDir == null ) {
                setLabelIcon(icnLocate, "/home/facetoe/tmp/crossIcon.png");
                cancel(true);
            } else {
                setLabelIcon(icnLocate, "/home/facetoe/tmp/system_tick_alt_03.png");
            }

            downloadSource();
            extractSource();
            setUpDefaultProfile(docDir);
            parseDocs(docDir);
            System.out.println(JReaderSetup.isSetup());
            return true;
        }

        @Override
        protected void done() {
            try {
                get();
            } catch ( InterruptedException e ) {
                e.printStackTrace();
            } catch ( ExecutionException e ) {
                e.printStackTrace();
            } catch ( CancellationException e ) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SetupWindow();
            }
        });
    }


}
